### ISSUE TITLE
Error adding simplifiedtimesheet

### ISSUE THREAD

**Issue by aamadou** [opefitoo/inur.django#45]
Request Method: | POST
-- | --
https://ahmedinur.herokuapp.com/admin/invoices/simplifiedtimesheet/add/
3.0.7
IndexError
list index out of range
/app/.heroku/python/lib/python3.8/site-packages/django/db/models/query.py in __getitem__, line 1461
/app/.heroku/python/bin/python
3.8.3
['/app/.heroku/python/bin',  '/app',  '/app/.heroku/python/lib/python38.zip',  '/app/.heroku/python/lib/python3.8',  '/app/.heroku/python/lib/python3.8/lib-dynload',  '/app/.heroku/python/lib/python3.8/site-packages']
sam, 20 Jui 2020 20:43:18 +0200
Environment:

Request Method: POST
Request URL: https://ahmedinur.herokuapp.com/admin/invoices/simplifiedtimesheet/add/

Django Version: 3.0.7
Python Version: 3.8.3
Installed Applications:
('django.contrib.admin',
 'dal',
 'dal_select2',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'gdstorage',
 'rest_framework',
 'rest_framework.authtoken',
 'constance',
 'constance.backends.database',
 'invoices',
 'api',
 'corsheaders')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.auth.middleware.RemoteUserMiddleware',
 'django_currentuser.middleware.ThreadLocalUserMiddleware')

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1638, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1565, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/app/invoices/admin.py", line 374, in save_model
    obj.employee = current_user[0]
  File "/app/.heroku/python/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in __getitem__
    return list(self)[k]

Exception Type: IndexError at /admin/invoices/simplifiedtimesheet/add/
Exception Value: list index out of range

**Comment by mehditerraneen** [comment]
is it still valid ?
