### ISSUE TITLE
Error adding new employee

### ISSUE THREAD

**Issue by aamadou** [opefitoo/inur.django#46]
Environment:

Request Method: POST
Request URL: https://ahmedinur.herokuapp.com/admin/invoices/employee/add/

Django Version: 3.0.7
Python Version: 3.8.3
Installed Applications:
('django.contrib.admin',
 'dal',
 'dal_select2',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'gdstorage',
 'rest_framework',
 'rest_framework.authtoken',
 'constance',
 'constance.backends.database',
 'invoices',
 'api',
 'corsheaders')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.auth.middleware.RemoteUserMiddleware',
 'django_currentuser.middleware.ThreadLocalUserMiddleware')

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1638, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1565, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1081, in save_model
    obj.save()
  File "/app/.heroku/python/lib/python3.8/site-packages/django/db/models/base.py", line 745, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/app/.heroku/python/lib/python3.8/site-packages/django/db/models/base.py", line 793, in save_base
    post_save.send(
  File "/app/.heroku/python/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 173, in send
    return [
  File "/app/.heroku/python/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 174, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/app/invoices/timesheet.py", line 120, in medical_prescription_clean_gdrive_post_delete
    gd_storage.update_folder_permissions_v3(path, email, has_access)
  File "/app/invoices/storages.py", line 113, in update_folder_permissions_v3
    self._drive_service.permissions().insert(fileId=folder_data["id"], body=p.raw).execute()

Exception Type: AttributeError at /admin/invoices/employee/add/
Exception Value: 'Resource' object has no attribute 'insert'

**Comment by mehditerraneen** [comment]
is it still valid ?
